Schism Tracker 0.18a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP LN_S RANLIB ac_ct_RANLIB SDL_CONFIG SDL_CFLAGS SDL_LIBS USE_NON_TRACKED_TYPES_TRUE USE_NON_TRACKED_TYPES_FALSE HAVE_LIBID3TAG_TRUE HAVE_LIBID3TAG_FALSE HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE USE_SAMPLE_TYPES_TRUE USE_SAMPLE_TYPES_FALSE EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP LN_S RANLIB ac_ct_RANLIB SDL_CONFIG SDL_CFLAGS SDL_LIBS USE_NON_TRACKED_TYPES_TRUE USE_NON_TRACKED_TYPES_FALSE HAVE_LIBID3TAG_TRUE HAVE_LIBID3TAG_FALSE HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE USE_SAMPLE_TYPES_TRUE USE_SAMPLE_TYPES_FALSE EGREP LIBOBJS USE_ALSA_MIXER_TRUE USE_ALSA_MIXER_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -865,6 +865,7 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --disable-sdltest       Do not try to compile and run a test SDL program
+  --enable-alsa-mixer     Use Alsa for the master volume control
   --enable-extra-opt      Add extra optimizations (egcs/GCC >= 2.95 only)
   --enable-all-warnings   Enable ridiculous compiler warnings (GCC)
 
@@ -1709,7 +1710,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=schism
- VERSION=0.17a
+ VERSION=0.18a
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4655,85 +4656,6 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking for InitConfig in -lcoman" >&5
-echo $ECHO_N "checking for InitConfig in -lcoman... $ECHO_C" >&6
-if test "${ac_cv_lib_coman_InitConfig+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lcoman  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char InitConfig ();
-int
-main ()
-{
-InitConfig ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_coman_InitConfig=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_coman_InitConfig=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_coman_InitConfig" >&5
-echo "${ECHO_T}$ac_cv_lib_coman_InitConfig" >&6
-if test $ac_cv_lib_coman_InitConfig = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBCOMAN 1
-_ACEOF
-
-  LIBS="-lcoman $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: *** libcoman not found." >&5
-echo "$as_me: error: *** libcoman not found." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-
 
 if false; then
   USE_NON_TRACKED_TYPES_TRUE=
@@ -7022,6 +6944,25 @@ fi
 
 
 
+# Check whether --enable-alsa-mixer or --disable-alsa-mixer was given.
+if test "${enable_alsa_mixer+set}" = set; then
+  enableval="$enable_alsa_mixer"
+  alsa_mixer=$enableval
+else
+  alsa_mixer=no
+fi;
+
+
+if test "$alsa_mixer" = yes; then
+  USE_ALSA_MIXER_TRUE=
+  USE_ALSA_MIXER_FALSE='#'
+else
+  USE_ALSA_MIXER_TRUE='#'
+  USE_ALSA_MIXER_FALSE=
+fi
+
+
+
 # Check whether --enable-extra-opt or --disable-extra-opt was given.
 if test "${enable_extra_opt+set}" = set; then
   enableval="$enable_extra_opt"
@@ -7195,6 +7136,13 @@ if test -z "${USE_SAMPLE_TYPES_TRUE}" && test -z "${USE_SAMPLE_TYPES_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"USE_SAMPLE_TYPES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_SAMPLE_TYPES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${USE_ALSA_MIXER_TRUE}" && test -z "${USE_ALSA_MIXER_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_ALSA_MIXER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_ALSA_MIXER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -7805,6 +7753,8 @@ s,@USE_SAMPLE_TYPES_TRUE@,$USE_SAMPLE_TYPES_TRUE,;t t
 s,@USE_SAMPLE_TYPES_FALSE@,$USE_SAMPLE_TYPES_FALSE,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
+s,@USE_ALSA_MIXER_TRUE@,$USE_ALSA_MIXER_TRUE,;t t
+s,@USE_ALSA_MIXER_FALSE@,$USE_ALSA_MIXER_FALSE,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
